#!/bin/bash  
# chkconfig: 2345 98 5  
# description: script to start/stop network-at
# description: Together with a per X-session agent process the spice agent \
#              daemon enhances the spice guest user experience with client \
#              mouse mode, guest <-> client copy and paste support and more.

### BEGIN INIT INFO
# Provides: network-atd
# Required-Start: $local_fs messagebus
# Required-Stop: $local_fs messagebus
# Should-Start: $local_fs messagebus
# Should-Stop: $local_fs messagebus
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 2 3 4 6
# Short-Description: Agent daemon for Spice guests
# Description: Together with a per X-session agent process the spice agent
#	daemon enhances the spice guest user experience with client
#	mouse mode, guest <-> client copy and paste support and more.
### END INIT INFO

start()
{	
    PID=$(pidof network-at)
    if [ -z $PID ]
    then 
    network-at &
    fi
#   tail -f --pid=$PID /dev/null 1>/dev/null 2>&1		
    exit 0;	
}
stop()
{
     pkill network-at
}

case "$1" in
start)
     start &
    ;;
stop)
     stop
    ;;
restart)
     stop
     start
    ;;
*)
    echo "usage: network-atd start|stop|restart"
    exit 0;
esac
